### ISSUE TITLE
Missing provider_list.html

### ISSUE THREAD

**Issue by flackdl** [tiberiuana/django-allauth-templates-bootstrap4#1]
This project may still be a work in progress, but I noticed that the [login template](https://github.com/tiberiuana/django-allauth-templates-bootstrap4/blob/master/allauth_bootstrap4/templates/account/login.html) references `socialaccount/parts/provider_list.html` but it doesn't exist.

**Comment by tiberiuana** [comment]
I think that's somewhat acceptable, because that is a part of the base templates provided by allauth.

In any case, you are right that this is a work in progress and not ready for direct use. I'll add a warning to that effect to the README.

Thanks!
